### ISSUE TITLE
designing  Main page

### ISSUE THREAD

**Issue by sainathgajula** [vamshi9666/gandhi_darshan#4]
mentions all ideas regarding main page .

**Reference websites  :**

1.  [walk for water](https://www.walkforwater.in/)
2. National Youth Corps
3. Ministry of Youth Affair and Sports
4. National Youth Policy

**Comment by vamshi9666** [comment]
mentions all ideas regarding main page .

**Reference websites  :**

1.  [walk for water](https://www.walkforwater.in/)

**Comment by vamshi9666** [comment]
@sainathgajula  update this list of references with desired features .

**Comment by vamshi9666** [comment]
@sainathgajula  need to mention links for that .
